const fs = require('fs').promises;
const path = require('path');

class JobLogger {
  constructor() {
    this.logDir = 'C:/Users/armaa/OneDrive/Desktop/jobtool/job_logs';
    this.ensureLogDirExists();
  }

  async ensureLogDirExists() {
    try {
      await fs.access(this.logDir);
    } catch {
      await fs.mkdir(this.logDir, { recursive: true });
    }
  }

  /**
   * Logs scraping results with date-based organization
   * @param {Array} jobs - Array of job objects
   * @param {Object} summary - Summary of scraping results
   */
  async logScrapingResults(jobs, summary) {
    const scrapeDate = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
    const totalJobs = jobs.length;
    
    // Create main scrape log file
    const mainLogFile = `${scrapeDate}_${totalJobs}.md`;
    await this.createMainLogFile(mainLogFile, jobs, summary);

    // Group jobs by date posted and create individual files
    const jobsByDate = this.groupJobsByDatePosted(jobs);
    
    for (const [datePosted, jobsForDate] of Object.entries(jobsByDate)) {
      await this.createDateSpecificLogFile(datePosted, jobsForDate);
    }

    console.log(`📄 Created log files: ${mainLogFile} and ${Object.keys(jobsByDate).length} date-specific files`);
  }

  /**
   * Groups jobs by their date posted
   * @param {Array} jobs - Array of job objects
   * @returns {Object} Jobs grouped by date posted
   */
  groupJobsByDatePosted(jobs) {
    const grouped = {};
    
    jobs.forEach(job => {
      const datePosted = job.datePosted ? 
        new Date(job.datePosted).toISOString().split('T')[0] : 
        'unknown-date';
      
      if (!grouped[datePosted]) {
        grouped[datePosted] = [];
      }
      grouped[datePosted].push(job);
    });

    return grouped;
  }

  /**
   * Creates the main scraping log file
   * @param {string} filename - Name of the log file
   * @param {Array} jobs - Array of all jobs scraped
   * @param {Object} summary - Scraping summary
   */
  async createMainLogFile(filename, jobs, summary) {
    const timestamp = new Date().toLocaleString('en-US', {
      timeZone: 'America/Chicago',
      dateStyle: 'full',
      timeStyle: 'long'
    });

    const content = `# Job Scraping Log - ${filename.replace('.md', '')}

## Scraping Summary
- **Timestamp**: ${timestamp}
- **Total Jobs Scraped**: ${jobs.length}
- **New Jobs Saved**: ${summary.saved || 0}
- **Duplicates Skipped**: ${summary.duplicates || 0}
- **Errors**: ${summary.errors || 0}

## Jobs by Date Posted
${this.generateJobsByDateSummary(jobs)}

## All Jobs Scraped
${jobs.map((job, index) => this.formatJobForLog(job, index + 1)).join('\n\n')}

---
*Generated by JobTool Scraper*
`;

    const filePath = path.join(this.logDir, filename);
    await fs.writeFile(filePath, content, 'utf8');
  }

  /**
   * Creates date-specific log files for jobs posted on specific dates
   * @param {string} datePosted - Date when jobs were posted
   * @param {Array} jobs - Jobs posted on this date
   */
  async createDateSpecificLogFile(datePosted, jobs) {
    const filename = `posted_${datePosted}_${jobs.length}.md`;
    const timestamp = new Date().toLocaleString('en-US', {
      timeZone: 'America/Chicago',
      dateStyle: 'full',
      timeStyle: 'long'
    });

    const content = `# Jobs Posted on ${datePosted}

## Summary
- **Date Posted**: ${datePosted}
- **Last Updated**: ${timestamp}
- **Total Jobs**: ${jobs.length}

## Job Listings

${jobs.map((job, index) => this.formatJobForLog(job, index + 1)).join('\n\n')}

---
*Generated by JobTool Scraper*
`;

    const filePath = path.join(this.logDir, filename);
    await fs.writeFile(filePath, content, 'utf8');
  }

  /**
   * Generates a summary of jobs grouped by date posted
   * @param {Array} jobs - Array of job objects
   * @returns {string} Formatted summary
   */
  generateJobsByDateSummary(jobs) {
    const jobsByDate = this.groupJobsByDatePosted(jobs);
    
    return Object.entries(jobsByDate)
      .sort(([a], [b]) => b.localeCompare(a)) // Sort by date descending
      .map(([date, jobsForDate]) => `- **${date}**: ${jobsForDate.length} jobs`)
      .join('\n');
  }

  /**
   * Formats a single job for logging
   * @param {Object} job - Job object
   * @param {number} index - Job index
   * @returns {string} Formatted job entry
   */
  formatJobForLog(job, index) {
    return `### ${index}. ${job.company} - ${job.position}

- **Company**: ${job.company}
- **Position**: ${job.position}
- **Status**: ${job.status}
- **Date Posted**: ${job.datePosted ? new Date(job.datePosted).toLocaleDateString() : 'Unknown'}
- **Location**: ${job.location || 'Not specified'}
- **Salary Range**: ${job.salaryRange || 'Not specified'}
- **Application URL**: ${job.applicationUrl ? `[Apply Here](${job.applicationUrl})` : 'Not available'}
- **Job ID**: ${job._id}
${job.notes ? `- **Notes**: ${job.notes}` : ''}`;
  }

  /**
   * Creates a simple summary log entry
   * @param {Object} summary - Scraping summary
   */
  async logSummary(summary) {
    const timestamp = new Date().toISOString();
    const logEntry = `${timestamp} - Scraped: ${summary.saved} new, ${summary.duplicates} duplicates, ${summary.errors} errors\n`;
    
    const summaryLogPath = path.join(this.logDir, 'scraping_summary.log');
    await fs.appendFile(summaryLogPath, logEntry);
  }

  /**
   * Lists all log files in the directory
   * @returns {Array} Array of log filenames
   */
  async getLogFiles() {
    try {
      const files = await fs.readdir(this.logDir);
      return files.filter(file => file.endsWith('.md') || file.endsWith('.log'));
    } catch (error) {
      console.error('Error reading log directory:', error.message);
      return [];
    }
  }

  /**
   * Cleans up old log files (keeps last 30 days)
   */
  async cleanupOldLogs() {
    try {
      const files = await this.getLogFiles();
      const thirtyDaysAgo = new Date();
      thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

      for (const file of files) {
        const filePath = path.join(this.logDir, file);
        const stats = await fs.stat(filePath);
        
        if (stats.mtime < thirtyDaysAgo) {
          await fs.unlink(filePath);
          console.log(`🗑️ Cleaned up old log file: ${file}`);
        }
      }
    } catch (error) {
      console.error('Error cleaning up logs:', error.message);
    }
  }
}

module.exports = JobLogger;